apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: validation
  labels:
    tier: validation
spec:
  # modify replicas according to your case
  replicas: 0
  selector:
    matchLabels:
      tier: validation
  template:
    metadata:
      labels:
        tier: validation
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.7
        resources:
          requests:
            cpu: 1m